import Head from 'next/head';
import { useEffect } from 'react';
import { useRouter } from 'next/router';
import styles from '../styles/Home.module.css';
import { useStateValue } from '../contexts';

const Home = () => {
  // eslint-disable-next-line no-unused-vars
  const { state, dispatch } = useStateValue();
  const router = useRouter();

  useEffect(() => {
    if (!state.user.isAuthenticated) {
      router.push('/login');
    }
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>MeetMax</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main} />

      <footer className={styles.footer}>Footer</footer>
    </div>
  );
};

export default Home;
